// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIKY05CetEmQ5zS8pc-jbIs05uhqK5dqE',
    appId: '1:22843191179:web:08ad45328ba46cedfbc98e',
    messagingSenderId: '22843191179',
    projectId: 'farenow-user',
    authDomain: 'farenow-user.firebaseapp.com',
    databaseURL: 'https://farenow-user-default-rtdb.firebaseio.com',
    storageBucket: 'farenow-user.appspot.com',
    measurementId: 'G-B6LZBBKDZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoNrIQ_w6mdtkmxUNzYVPQtDBAJNZ2Tks',
    appId: '1:22843191179:android:7579b4e9b6e6263dfbc98e',
    messagingSenderId: '22843191179',
    projectId: 'farenow-user',
    databaseURL: 'https://farenow-user-default-rtdb.firebaseio.com',
    storageBucket: 'farenow-user.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj-b8x9ZLmgPdnGNoHdVMhGzPIdv4lWyQ',
    appId: '1:22843191179:ios:a27fb49b9613319afbc98e',
    messagingSenderId: '22843191179',
    projectId: 'farenow-user',
    databaseURL: 'https://farenow-user-default-rtdb.firebaseio.com',
    storageBucket: 'farenow-user.appspot.com',
    androidClientId: '22843191179-0agse31dskbc48ofun5rlrd50er57e0r.apps.googleusercontent.com',
    iosClientId: '22843191179-4gqq4c5efkp9bro69nc96341vfl6al46.apps.googleusercontent.com',
    iosBundleId: 'com.comp.farenow',
  );
}
