/// Generated by AssetsRefGenerator on 2022/06/10
class Res {
  static const String assets_images_imageView = "assets/images/imageView.png";
  static const String boypic1 = "assets/image 2x/boypic1.png";
  static const String boypic2 = "assets/image 2x/boypic2.png";
  static const String burgers = "assets/image 2x/burgers.png";
  static const String calculator = "assets/image 1.5x/calculator.png";
  static const String cashbook = "assets/image 1.5x/cashbook.png";
  static const String dp = "assets/image 2x/dp.png";
  static const String facebook = "assets/image 2x/facebook.png";
  static const String facebook_logo = "assets/images/facebook_logo.png";
  static const String foodBox = "assets/image 2x/foodBox.png";
  static const String foodpng = "assets/image 2x/foodpng.png";
  static const String fSupperpic = "assets/image 2x/fS upper pic.png";
  static const String google = "assets/image 2x/google.png";
  static const String handy = "assets/image 2x/handy.png";
  static const String home = "assets/image 1.5x/home.png";
  static const String ic_add = "assets/icons/ic_add.svg";
  static const String ic_address_placeholer =
      "assets/icons/ic_address_placeholer.svg";
  static const String ic_calendar = "assets/icons/ic_calendar.svg";
  static const String ic_mega_truck = "assets/icons/ic_mega_truck.svg";
  static const String ic_message = "assets/icons/ic_message.svg";
  static const String ic_mini_moto = "assets/icons/ic_mini_moto.svg";
  static const String ic_mini_truck = "assets/icons/ic_mini_truck.svg";
  static const String ic_navigation_arrow =
      "assets/icons/ic_navigation_arrow.svg";
  static const String ic_order_done = "assets/icons/ic_order_done.svg";
  static const String ic_pickup = "assets/icons/ic_pickup.svg";
  static const String ic_scooter = "assets/icons/ic_scooter.svg";
  static const String ic_tap_finger = "assets/icons/ic_tap_finger.svg";
  static const String ic_time = "assets/ic_time.svg";
  static const String ic_us_flag = "assets/icons/ic_us_flag.svg";
  static const String ic_van = "assets/icons/ic_van.svg";
  static const String image_five = "assets/icons/image_five.svg";
  static const String image_four = "assets/icons/image_four.svg";
  static const String image_one = "assets/icons/image_one.svg";
  static const String image_three = "assets/icons/image_three.svg";
  static const String image_two = "assets/icons/image_two.svg";
  static const String imageView = "assets/image 2x/imageView.png";
  static const String img_bar = "assets/images/img_bar.png";
  static const String img_finger_tap = "assets/images/img_finger_tap.png";
  static const String img_gallery = "assets/images/img_gallery.png";
  static const String img_google = "assets/images/img_google.png";
  static const String img_goole_map = "assets/images/img_goole_map.png";
  static const String img_logo = "assets/images/img_logo.png";
  static const String img_photo = "assets/images/img_photo.png";
  static const String img_profile_place_holder =
      "assets/images/img_profile_place_holder.jpg";
  static const String img_us_flag = "assets/images/img_us_flag.png";
  static const String login = "assets/images/login.png";
  static const String mapHeader = "assets/images/mapHeader.png";
  static const String mastercard = "assets/image 1.5x/mastercard.png";
  static const String preference = "assets/image 1.5x/preference.png";
  static const String project = "assets/image 2x/project.png";
  static const String service_placeholder =
      "assets/images/service_placeholder.png";
  static const String shopBackground = "assets/image 2x/shopBackground.png";
  static const String shopProfile = "assets/image 2x/shopProfile.png";
  static const String stock = "assets/image 1.5x/stock.png";
}
